drop table if exists db1b_markets;

create table db1b_markets
(
  itinerary_id numeric(16) not null,
  market_id numeric(16) not null,
  number_coupons numeric(6) not null,
  year numeric(4) not null,
  quarter int not null,
  origin char(3) not null,
  number_origin_airports numeric(2) not null,
  origin_city_code numeric(6) not null,
  origin_country_code char(3) not null,
  origin_state_fips numeric(2) not null,
  origin_state char(2) not null,
  origin_state_name char(50) not null,
  origin_wac numeric(4) not null,
  destination char(3) not null,
  number_destination_airports numeric(2) not null,
  destination_city_code numeric(6) not null,
  destination_country_code char(3) not null,
  destination_state_fips numeric(2) not null,
  destination_state char(2) not null,
  destination_state_name char(50) not null,
  destination_wac numeric(4) not null,
  airport_group char(51) not null,
  airport_wac_group char(38) not null,
  ticketing_carrier_change numeric(1, 0) not null,
  ticketing_carrier_group char(35) not null,
  operating_carrier_change numeric(1, 0) not null,
  operating_carrier_group char(35) not null,
  reporting_carrier char(6) not null,
  ticketing_carrier char(6) not null,
  operating_carrier char(6) not null,
  bulk_fare_flag numeric(1) not null,
  passengers numeric(4) not null,
  fare numeric(7, 2) not null,
  distance numeric(5) not null,
  distance_group numeric(2) not null,
  miles_flown numeric(5) not null,
  nonstop_miles numeric(5, 0) not null,
  itinerary_geography_type numeric(1) not null,
  market_geography_type numeric(1) not null
)
partition by list (quarter)
(	partition p_q1 values in (1),
	partition p_q2 values in (2),
	partition p_q3 values in (3),
	partition p_q4 values in (4)
);